<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.NETCore.App" Version="2.2.8" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Horyzonty_Nauki.Domain\Horyzonty_Nauki.Domain.csproj" />
    <ProjectReference Include="..\Horyzonty_Nauki.Infrastructure\Horyzonty_Nauki.Infrastructure.csproj" />
  </ItemGroup>

</Project>
